import './globals.css'
import NavMenu from '@/components/Nav'
import Footer from '@/components/Footer'
import '../../public/assets/css/style.css'
import 'bootstrap/dist/css/bootstrap.css'
import 'aos/dist/aos.css';
export const metadata = {
  title: 'Charge Construct',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={''}>
        <NavMenu/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
