import { useEffect, useState } from 'react'
import NavMenu from '@/components/Nav'
import Footer from '@/components/Footer'
import Head from 'next/head'
import ContactDetails from '@/components/GeneralDetails/ContactDetails'
import '../../public/assets/css/style.css'
import 'bootstrap/dist/css/bootstrap.css'
import 'aos/dist/aos.css';
import Scroll from './SmoothScroll/SmoothScroll'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children,title,metaDescription,viewClass }) {
  const [isTop, setIsTop] = useState(true);

  useEffect(() => {
    const handleScroll = () => {
      const scrollTop = window.scrollY;
      const shouldBeTop = scrollTop === 0;

      setIsTop(shouldBeTop);
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
      <>
         <Head>
        <title>{title}</title>
        <meta name="description" content={metaDescription ? metaDescription : 'Charge Construct'} />
      </Head>
        <NavMenu addedCLass={viewClass}/>
        <Scroll/>
       <main>
        {children}
        </main>
        <Footer/>
        </>
  )
}

Layout.defaultProps = {
  title: 'Charge Construct',
  description: '',
  viewClass : 'innerpages'
}
