import { useEffect, useState } from 'react'
import NavMenu from '@/components/Nav'
import Footer from '@/components/Footer'
import Head from 'next/head'
import ContactDetails from '@/components/GeneralDetails/ContactDetails'
import '../../public/assets/css/style.css'
import 'bootstrap/dist/css/bootstrap.css'
import 'aos/dist/aos.css';
import Scroll from './SmoothScroll/SmoothScroll'
export const metadata = {
  title: 'Charge Construct | Power On!',
  description: 'Generated by create next app',
}

export default function Layout({ children,title,metaDescription,viewClass }) {
  
  return (
      <>
         <Head>
          <></>
        <title>{title}</title>
        <meta name="description" content={metaDescription ? metaDescription : 'Charge Construct'} />
        <link rel="icon" type="image/png" sizes="32x32" href="../assets/images/favicon.png"/>

      </Head>
        <NavMenu addedCLass={viewClass}/>
     
       <main>
       <Scroll/>
        {children}
        </main>
        
        <Footer/>
        </>
  )
}

Layout.defaultProps = {
  title: 'Charge Construct',
  description: '',
  viewClass : 'innerpages'
}
